table:
  name: repo_sync_settings
  schema: public
object_relationships:
- name: repo
  using:
    foreign_key_constraint_on: repo_id
- name: repo_sync_type
  using:
    foreign_key_constraint_on: sync_type
