version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  init:
    build:
      context: .
    image: fuse-worker:local
    entrypoint: migrate
    command: ["-database", "postgres://postgres:password@postgres:5432/postgres?sslmode=disable", "-path", "migrations/", "up"]
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: postgres
    depends_on:
      - postgres

  worker:
    image: fuse-worker:local
    stop_grace_period: 10m
    depends_on:
      - init
      - postgres
    environment:
      POSTGRES_CONNECTION: postgres://postgres:password@postgres:5432/postgres
      GITHUB_RATE_LIMIT: 1/2
    env_file:
      - .env
    ports:
      - 3301:8080

  grafana:
    image: grafana/grafana-oss:latest
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGDATABASE: postgres
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    volumes:
      - grafana_lib:/var/lib/grafana
      - grafana_etc:/etc/grafana
      - grafana_log:/var/log/grafana
      - ./scripts/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning
      - ./scripts/grafana/dashboards:/var/lib/grafana/dashboards/

volumes:
  db_data:
  grafana_lib:
  grafana_etc:
  grafana_log:
