name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: mergestat-linux-amd64
          - os: macos-latest
            asset_name: mergestat-macos-amd64

    steps:
    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.5
      id: go

    - name: Check out source
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install libgit2
      run: sudo ./scripts/install_libgit2.sh

    - name: Vet
      run: make vet

    - name: Lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.44.2
        make lint-ci
